### ISSUE TITLE
Step 1 Stopped

### ISSUE THREAD

**Issue by Nostraquedeo** [loki-project/loki-network-control-panel#1]
I put in: sudo apt install qt5-default qtdeclarative5-dev qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-dialogs qml-module-qt-labs-platform

and I got this:
Get:66 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 qtdeclarative5-dev amd64 5.9.5-0ubuntu1.1 [529 kB]
Fetched 10.2 MB in 7s (1,404 kB/s)                                            
Extracting templates from packages: 100%
dpkg: unrecoverable fatal error, aborting:
 unknown group '_loki' in statoverride file
E: Sub-process /usr/bin/dpkg returned an error code (2)

Could this be because I have loki router already running?

**Comment by notlesh** [comment]
It sounds like `dpkg` is unhappy about something unrelated to this project and the command you ran. (This project actually has no install- or compile-time dependencies on any other `loki` project or any related user-account; it communicates only over a JSON-API.)

According to [this Ask Ubuntu question](https://askubuntu.com/questions/335538/unknown-user-in-statoverride-file), there may be a problem with the file `/var/lib/dpkg/statoverride`. If the answers in that question are unhelpful, let me know.

**Comment by notlesh** [comment]
Closing this out since I haven't heard any follow up.
