### ISSUE TITLE
The lokinet logo should be used, not the loki logo 

### ISSUE THREAD

**Issue by Lucifer1903** [loki-project/loki-network-control-panel#29]
![sketch-1584192394281](https://user-images.githubusercontent.com/29006257/77563043-aa64ec00-6eb8-11ea-932e-fd06cf3b412f.png)

**Comment by notlesh** [comment]
As of `v0.7.0`, this is is what we're using -- correct me if I'm wrong.

**Comment by jagerman** [comment]
https://github.com/loki-project/loki-network-control-panel/blob/master/res/images/icon.png since PR #27 

(Also there are debs pushed for it now for Ubuntu Debian.  Unofficially officially until announcement, or something like that.)

**Comment by Lucifer1903** [comment]
Oh okay, my mistake. I noticed it a while ago and only just got around to putting the issue on github.

**Comment by Lucifer1903** [comment]
The correct logo is being used now.
