### ISSUE TITLE
Lokinet-gui crashes on start

### ISSUE THREAD

**Issue by Many98** [loki-project/loki-network-control-panel#94]
I have recently installed lokinet and lokinet-gui on Ubuntu 18.04 following this guide https://docs.loki.network/Lokinet/Guides/LokinetGuiGuide/#turn-lokinet-off-and-on . 

Gui app crashes immediately when I run it and lokinet seems to not work as well.

**Comment by majestrate** [comment]
#95 fixed this in my VM

**Comment by majestrate** [comment]
this got fixed by #95 (allegedly)
